// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/client.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataRequest struct {
	Hashtag              string   `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	Limit                string   `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92480c0dace3ff15, []int{0}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetHashtag() string {
	if m != nil {
		return m.Hashtag
	}
	return ""
}

func (m *DataRequest) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

type DataResponse struct {
	Tweet                []*DataTweet `protobuf:"bytes,1,rep,name=tweet,proto3" json:"tweet,omitempty"`
	Lenght               int32        `protobuf:"varint,2,opt,name=lenght,proto3" json:"lenght,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92480c0dace3ff15, []int{1}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetTweet() []*DataTweet {
	if m != nil {
		return m.Tweet
	}
	return nil
}

func (m *DataResponse) GetLenght() int32 {
	if m != nil {
		return m.Lenght
	}
	return 0
}

type DataTweet struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Tweet                string   `protobuf:"bytes,4,opt,name=tweet,proto3" json:"tweet,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Hashtags             []string `protobuf:"bytes,6,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTweet) Reset()         { *m = DataTweet{} }
func (m *DataTweet) String() string { return proto.CompactTextString(m) }
func (*DataTweet) ProtoMessage()    {}
func (*DataTweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_92480c0dace3ff15, []int{2}
}

func (m *DataTweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTweet.Unmarshal(m, b)
}
func (m *DataTweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTweet.Marshal(b, m, deterministic)
}
func (m *DataTweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTweet.Merge(m, src)
}
func (m *DataTweet) XXX_Size() int {
	return xxx_messageInfo_DataTweet.Size(m)
}
func (m *DataTweet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTweet.DiscardUnknown(m)
}

var xxx_messageInfo_DataTweet proto.InternalMessageInfo

func (m *DataTweet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataTweet) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DataTweet) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *DataTweet) GetTweet() string {
	if m != nil {
		return m.Tweet
	}
	return ""
}

func (m *DataTweet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataTweet) GetHashtags() []string {
	if m != nil {
		return m.Hashtags
	}
	return nil
}

func init() {
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*DataResponse)(nil), "DataResponse")
	proto.RegisterType((*DataTweet)(nil), "DataTweet")
}

func init() {
	proto.RegisterFile("protos/client.proto", fileDescriptor_92480c0dace3ff15)
}

var fileDescriptor_92480c0dace3ff15 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0x4d, 0xd2, 0xc4, 0x66, 0x5a, 0x3d, 0x8c, 0x22, 0x4b, 0x41, 0x08, 0x39, 0xd5, 0x4b,
	0x84, 0x7a, 0xf0, 0xe4, 0x41, 0x50, 0xf4, 0x1c, 0xbc, 0xcb, 0xda, 0x0c, 0xc9, 0x42, 0xba, 0xa9,
	0xd9, 0xa9, 0xbe, 0x8c, 0x0f, 0x2b, 0xfb, 0xa7, 0x25, 0xb7, 0xfd, 0x7e, 0xb3, 0x3b, 0xf3, 0xed,
	0xc0, 0xd5, 0x7e, 0x1c, 0x78, 0x30, 0xf7, 0xdb, 0x5e, 0x91, 0xe6, 0xca, 0x51, 0xf9, 0x04, 0x8b,
	0x17, 0xc9, 0xb2, 0xa6, 0xef, 0x03, 0x19, 0x46, 0x01, 0xe7, 0x9d, 0x34, 0x1d, 0xcb, 0x56, 0x44,
	0x45, 0xb4, 0xce, 0xeb, 0x23, 0xe2, 0x35, 0xa4, 0xbd, 0xda, 0x29, 0x16, 0xb1, 0xcb, 0x3d, 0x94,
	0xef, 0xb0, 0xf4, 0xcf, 0xcd, 0x7e, 0xd0, 0x86, 0xb0, 0x80, 0x94, 0x7f, 0x89, 0x58, 0x44, 0x45,
	0xb2, 0x5e, 0x6c, 0xa0, 0xb2, 0xd5, 0x0f, 0x9b, 0xd4, 0xbe, 0x80, 0x37, 0x90, 0xf5, 0xa4, 0xdb,
	0xce, 0x37, 0x4a, 0xeb, 0x40, 0xe5, 0x5f, 0x04, 0xf9, 0xe9, 0x32, 0x5e, 0x42, 0xac, 0x9a, 0xa0,
	0x10, 0xab, 0x06, 0x57, 0x30, 0x3f, 0x18, 0x1a, 0xb5, 0xdc, 0x51, 0x10, 0x38, 0x31, 0xde, 0x02,
	0x6c, 0x47, 0x92, 0x4c, 0xcd, 0xa7, 0x64, 0x91, 0xb8, 0x6a, 0x1e, 0x92, 0x67, 0xb6, 0xe2, 0x5e,
	0x69, 0xe6, 0xc5, 0xbd, 0x06, 0xc2, 0xcc, 0x35, 0x4b, 0x5d, 0xe8, 0xce, 0x76, 0x48, 0xf8, 0xad,
	0x11, 0x59, 0x91, 0xd8, 0x21, 0x47, 0xde, 0x3c, 0x02, 0x58, 0xbb, 0x57, 0xdd, 0x2a, 0x4d, 0x78,
	0x07, 0xf3, 0x37, 0xf5, 0x43, 0x36, 0xc1, 0x65, 0x35, 0x59, 0xe0, 0xea, 0xa2, 0x9a, 0xee, 0xa3,
	0x3c, 0xfb, 0xca, 0xdc, 0x9e, 0x1f, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xd8, 0x61, 0x24,
	0x7e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataEngineClient is the client API for DataEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataEngineClient interface {
	GiveData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type dataEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDataEngineClient(cc grpc.ClientConnInterface) DataEngineClient {
	return &dataEngineClient{cc}
}

func (c *dataEngineClient) GiveData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/DataEngine/GiveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataEngineServer is the server API for DataEngine service.
type DataEngineServer interface {
	GiveData(context.Context, *DataRequest) (*DataResponse, error)
}

// UnimplementedDataEngineServer can be embedded to have forward compatible implementations.
type UnimplementedDataEngineServer struct {
}

func (*UnimplementedDataEngineServer) GiveData(ctx context.Context, req *DataRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveData not implemented")
}

func RegisterDataEngineServer(s *grpc.Server, srv DataEngineServer) {
	s.RegisterService(&_DataEngine_serviceDesc, srv)
}

func _DataEngine_GiveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).GiveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataEngine/GiveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).GiveData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataEngine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataEngine",
	HandlerType: (*DataEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GiveData",
			Handler:    _DataEngine_GiveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/client.proto",
}
